const data = {
  code: 0,
  result: {
    standardAdList: [],
    liteAdList: [
      {
        _id: "66598f406a36af001d813f9d",
        gymName: "시청 피트니스온",
        gymPhotoBig:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18fcdd79463342aa28/2Zw9JCqfv33TgjXzG2j9NCEpp6eXri6Pk3zG.Big_15.jpg",
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18fcdd79463342aa28/2YBLc2P6ECeDH15A7K13xykGCCSJhkEMDqo5.Small_15.jpg",
        address: "서울 중구 무교동",
        location: [126.9796085839833, 37.56731991944422],
        isWomenOnly: false,
        isReservationRequired: true,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스", "골프"],
        program: {
          free: "OT 2회 무료",
        },
        service: {
          free: "사우나, 바디워시, 샴푸 제공",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: true,
          lowestPrice: 455000,
          originalPrice: 495000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: 16,
        },
        review: {
          rate: 5,
          count: 16,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
      },
      {
        _id: "65fb96e46d09b7001d9d1fa0",
        gymName: "시청 무브짐앤무브맥스PT",
        gymPhotoBig:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18e5ec56c2a2c8a2e4/43D6ieGSQgRbwJmudqjrWKoD1VnvZDusnori.background_photo.jpg",
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18e5ec56c2a2c8a2e4/2WiSHkcu3B7NDn3bQy7zDzxXfUQVYzS9t9hk.list_photo.jpg",
        address: "서울 중구 서소문동",
        location: [126.97363348811612, 37.563331828432155],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "",
        },
        service: {
          free: "샤워실 / 수건 / 대형제빙기 / ️ 무료주차 2시간 30분 / 인바디 측정",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: true,
          lowestPrice: 377000,
          originalPrice: 470000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: 6,
        },
        review: {
          rate: 5,
          count: 7,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
      },
    ],
    centerList: [
      {
        _id: "62e913e9f9efad001d8f473e",
        gymName: "을지로 펄스핏 피트니스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1825e75c7082a576a4/4K8gHYEb5rWJtJKJpHwCnL8V5xTn6yNPKGD5LcYzAx9E.jpg",
        address: "서울 중구 을지로1가",
        location: [126.97951563415681, 37.5657386554874],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "유료주차 가능",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 396000,
          originalPrice: 396000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 4.93,
          count: 29,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "6321454882a1c2001d14e202",
        gymName: "종로 스포짐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18339f6a20fe5f94e/kXjvwH8c7VMy1K45LqKEzxNAyFcnP766Nz36VAyF68.jpg",
        address: "서울 종로구 서린동",
        location: [126.98130878139783, 37.56932942118991],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T", "기구필라테스", "G.X"],
        program: {
          free: "",
        },
        service: {
          free: "운동복 / 수건 / 양말 / / 샴푸 / 바디워시 / ️ 주차 2시간 가능",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 480000,
          originalPrice: 480000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 4.81,
          count: 16,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "632d2a6967a7ff001d507f2b",
        gymName: "광화문 이스트 골프라운지",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/183686dadc937bb767/2aFefNkefcTcYBSxbxtQhqGBDgxiDjSERsa6.photo_2.900x676.jpg",
        address: "서울 종로구 종로1가",
        location: [126.97989631253533, 37.57070320710209],
        isWomenOnly: false,
        isReservationRequired: true,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["골프"],
        program: {
          free: "O.T",
        },
        service: {
          free: "주차 2시간",
        },
        price: {
          name: "MEMBERSHIP🏌️‍♂️50min",
          count: null,
          isLowestPrice: false,
          lowestPrice: 3000000,
          originalPrice: 3000000,
          period: 6,
          priceType: "period",
          itemTags: ["골프"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "62c3eefd99269f001d846287",
        gymName: "시청 요가타운 서소문교육원",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/181cd5d8c511a9b79a/4K8g81Hip8Do9PTbbeREKtTTABr6BLQQD7NtWzShtJc8.jpg",
        address: "서울 중구 서소문동",
        location: [126.9727450920451, 37.56303429786593],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["요가", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "요가복 / 수건",
        },
        price: {
          name: "요가 (주 2회)",
          count: null,
          isLowestPrice: false,
          lowestPrice: 1400000,
          originalPrice: 1400000,
          period: 12,
          priceType: "period",
          itemTags: ["요가"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 4,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "606178dd43115b0039225ae0",
        gymName: "명동 은행회관 헬스클럽",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1787cc020665232fec/4K7pCDmb1Rr5UHrvRJyUA82i4ME2ZEYJMwqnaSxuf384.jpg",
        address: "서울 중구 명동1가",
        location: [126.98544300866244, 37.564987949323516],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "사우나"],
        program: {
          free: "O.T (상시 지도) / G.X수업 (스트레칭 / 요가)",
        },
        service: {
          free: "주차 2시간 / 운동복 / 수건 / Wi-fi / 사우나",
        },
        price: {
          name: "헬스+스파+사우나",
          count: null,
          isLowestPrice: false,
          lowestPrice: 1512000,
          originalPrice: 1512000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스", "사우나"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 38,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "63020a6a253e7e001dc8e1e0",
        gymName: "시청 겟투잇 피트니스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/182bff8af4a1e60773/2WQFyg7sWAqyqkDEQVKE5GRYSfMJFy2mKwRj.list_photo.jpg",
        address: "서울 서대문구 미근동",
        location: [126.97122245295341, 37.5638223083948],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "",
        },
        service: {
          free: "️운동복+수건",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 528000,
          originalPrice: 528000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 1,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "5faa2611cf2a1a001d936319",
        gymName: "을지로 크로스핏 삼손",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/175b0a4b4fe567e322/2WjeJZnzEMeavHrbhXwVEMwPK76mZMMcitug.list_photo.jpg",
        address: "서울 중구 장교동",
        location: [126.98709621978122, 37.567145281087775],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["크로스핏"],
        program: {
          free: "",
        },
        service: {
          free: "WI-FI / 수건 / 샤워용품 / 인바디",
        },
        price: {
          name: "크로스핏  회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 1200000,
          originalPrice: 1200000,
          period: 6,
          priceType: "period",
          itemTags: ["크로스핏"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 14,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "6059847543115b00392248e0",
        gymName: "을지로 피트니스101",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1785dad6b2e639542/kXYY4y8ZNcFA177fEscdJ7i7Xc1tjp7wxMvyUTFnxx.jpg",
        address: "서울 중구 저동1가",
        location: [126.98732734452591, 37.565276666657034],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T", "기구필라테스"],
        program: {
          free: "1:1 P.T 체험권 (2회)",
        },
        service: {
          free: "️주차 (평일: 2시간/주말 4시간 ) / 수건 / Wi-fi / 태닝 / 샐러드바",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 660000,
          originalPrice: 660000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 17,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "63bbc28a33db2b001d47b24e",
        gymName: "회현 더코어필라테스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/185956fee3c5831ac4/2WRTMU7LK8bzvsZtTAHKd15ut5N9n6qx3fZT.Small_231128_회현_더코어필라테스_34.jpg",
        address: "서울 중구 회현동1가",
        location: [126.98055017543099, 37.55922913034157],
        isWomenOnly: false,
        isReservationRequired: true,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["기구필라테스", "필라테스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "️주차 2시간 가능 / ️수건 / 샤워실 / 락커",
        },
        price: {
          name: "5:1그룹 필라테스 (주 2회)",
          count: 96,
          isLowestPrice: true,
          lowestPrice: 1612800,
          originalPrice: 2000000,
          period: null,
          priceType: "count",
          itemTags: ["필라테스"],
          lowestPriceRemainingCount: 5,
        },
        review: {
          rate: 5,
          count: 2,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "5fcd89cacf2a1a001d987efa",
        gymName: "광화문 MCT GYM",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1763ae23e593353c36/4K7ono7B2uMP7whX3mHCKxQHBxYWgsxNDv4ej85DzT8C.jpg",
        address: "서울 종로구 내수동",
        location: [126.97099309787437, 37.57260651126412],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "O.T (1회 50분)",
        },
        service: {
          free: "주차 (2시간) / WI-FI / 수건",
        },
        price: {
          name: "헬스",
          count: null,
          isLowestPrice: false,
          lowestPrice: 880000,
          originalPrice: 880000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 3,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "6344f74658fe3f001d9a1f39",
        gymName: "서대문역 서대문주짓수",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/183c565e970530dc80/2YVNiEVbwSfBF1YhLzr2ZXL4w2ksDe8gYjBZ.Small_다운로드 (6).jpg",
        address: "서울 서대문구 충정로2가",
        location: [126.96592187885915, 37.565224199017344],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["주짓수", "복싱", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "샤워실 / 락커 / Wi-fi",
        },
        price: {
          name: "주짓수 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 1500000,
          originalPrice: 1500000,
          period: 12,
          priceType: "period",
          itemTags: ["주짓수"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 5,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "66aafedb01d0e4001dc4a9f4",
        gymName: "서대문역 타임피티",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1910bf3879eaefb4d/2WP49SHuNo8CHkNog864uAjPCpGstCbDRt6L.list_photo.jpg",
        address: "서울 종로구 교남동",
        location: [126.96470644307217, 37.56838858989958],
        isWomenOnly: false,
        isReservationRequired: true,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["P.T"],
        program: {
          free: "",
        },
        service: {
          free: "수건 / 개인락커 / 주차무료",
        },
        price: {
          name: "PT 회원권",
          count: 48,
          isLowestPrice: true,
          lowestPrice: 2430000,
          originalPrice: 2700000,
          period: null,
          priceType: "count",
          itemTags: ["P.T"],
          lowestPriceRemainingCount: 5,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "5e09c65e5b93422540d20883",
        gymName: "서대문 짐피닉스 PT스튜디오",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/16f562edf6c3c40cca/2ZyZEYGoMV4zsTq6NQmdbojuQKG7UxBwvvbJ.센터 Small 복사.jpg",
        address: "서울 종로구 교남동",
        location: [126.96453668497348, 37.56852887067164],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["그룹P.T", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "수건 / 샴푸&바디워시 /",
        },
        price: {
          name: "짐피닉스 소그룹P.T (월 10회)",
          count: null,
          isLowestPrice: false,
          lowestPrice: 1111000,
          originalPrice: 1111000,
          period: 6,
          priceType: "period",
          itemTags: ["그룹P.T", "P.T"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 2,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "59e4360761a74379ba5738ac",
        gymName: "서대문역 VIP 휘트니스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/15f23730f0d4746062/4K6CpJYkn2FxX8CjH1MrrvAGtZsr251Gk9JabUig3AHn.jpg",
        address: "서울 서대문구 충정로2가",
        location: [126.964323, 37.564755],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "‍ O.T (3개월 이상 등록시 - 30분 1회 )",
        },
        service: {
          free: "운동복 / 수건 / 샤워실 / 인바디 / 주차는 리프트안 승용차만 2시간가능",
        },
        price: {
          name: "헬스+운동복",
          count: null,
          isLowestPrice: false,
          lowestPrice: 462000,
          originalPrice: 462000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 4.95,
          count: 14,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "6639a931f09ceb001d67b62f",
        gymName: "무악 독립문 체육관",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18f513ce91510774ed/2WNipV3HGqdf63akVGGn4YTYXHCo8hSCDCvd.list_photo.jpg",
        address: "서울 종로구 무악동",
        location: [126.95918508308492, 37.574261298603105],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "",
        },
        service: {
          free: "️운동복+수건 / ️주차 2시간",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 550000,
          originalPrice: 550000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "64422f458ec65b001d34507d",
        gymName: "후암 텐세그리티",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/187a288a71d526ed1f/4K8hKdqZKtdWuf41K5pYKjDPJVCj4uSPSvrJuvqPm7Hz.jpg",
        address: "서울 용산구 후암동",
        location: [126.98349228750746, 37.54886810307899],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T", "기구필라테스"],
        program: {
          free: "",
        },
        service: {
          free: "주차 시간제한 없음",
        },
        price: {
          name: "헬스 (+운동복+락커)",
          count: null,
          isLowestPrice: false,
          lowestPrice: 1200000,
          originalPrice: 1200000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "599089bcb3d73d2cc88da985",
        gymName: "아현 247휘트니스&필라테스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/15ddc9a081548955/ArtGhaofpWo3oHeSq1Vn6WiZBdmwaKnpjKq33B5ax.jpg",
        address: "서울 서대문구 북아현동",
        location: [126.957526, 37.557779],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "기구필라테스"],
        program: {
          free: "",
        },
        service: {
          free: "수건 / Wi-Fi / 반신욕기 이용",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 396000,
          originalPrice: 396000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 4.65,
          count: 28,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "64b7090ce53cb5001dd7ba78",
        gymName: "공덕 헤이점핑",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1896afb5a7315e672d/2YAwMi5SJdYWshN7ZWDogUSDgUZg85GjNhbM.센터 Small 복사.jpg",
        address: "서울 마포구 공덕동",
        location: [126.96243422869632, 37.55121488728981],
        isWomenOnly: false,
        isReservationRequired: true,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["점핑운동"],
        program: {
          free: "",
        },
        service: {
          free: "신발보관 / 프로틴쉐이크제공 /",
        },
        price: {
          name: "기간 이용권",
          count: null,
          isLowestPrice: true,
          lowestPrice: 1382400,
          originalPrice: 1728000,
          period: 12,
          priceType: "period",
          itemTags: ["점핑운동"],
          lowestPriceRemainingCount: 5,
        },
        review: {
          rate: 4.9,
          count: 10,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "5b6c6c20729a8461514bea7c",
        gymName: "애오개 헬스존",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1651f865fbf5da8d11/2Y9Kv1ReEdgY83knduJVLifwzAd1L1RwysoY.Small_231212_애오개_헬스존_07.jpg",
        address: "서울 마포구 공덕동",
        location: [126.960333, 37.550072],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "️주차 3시간 / ️수건 + 탈의실 락커",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: true,
          lowestPrice: 380000,
          originalPrice: 400000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: 19,
        },
        review: {
          rate: 4.85,
          count: 20,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "60472b2e43115b0039221b1b",
        gymName: "숙대입구 풍산복싱체육관",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1781600acb02b55fcb/2ZyUmTAfiYPSpYmxmQHE8Jhju7nrEbbPM7CY.Small_012.jpg",
        address: "서울 용산구 갈월동",
        location: [126.97154759870462, 37.54534459037155],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["복싱"],
        program: {
          free: "",
        },
        service: {
          free: "️수건 / 라커 / WI-FI",
        },
        price: {
          name: "복싱 회원권",
          count: null,
          isLowestPrice: true,
          lowestPrice: 1080000,
          originalPrice: 1200000,
          period: 12,
          priceType: "period",
          itemTags: ["복싱"],
          lowestPriceRemainingCount: 10,
        },
        review: {
          rate: 5,
          count: 8,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
    ],
  },
};

const newdata = data.result.centerList;

const main = document.createElement("main");
const container = document.createElement("section");
container.classList.add("container");

newdata.forEach((v) => {
  const card = document.createElement("div");
  card.classList.add("card");

  const album = document.createElement("div");
  album.classList.add("album");
  const img = document.createElement("img");
  img.src = v.gymPhotoSmall;
  album.appendChild(img);
  card.appendChild(album);

  const info = document.createElement("div");
  info.classList.add("info");

  const category = document.createElement("span");
  category.classList.add("category");
  category.innerText = v.tags;
  const gymName = document.createElement("span");
  gymName.classList.add("category");
  gymName.innerText = v.gymName;
  const price = document.createElement("span");
  price.classList.add("price");
  price.innerText = v.price.originalPrice;
  const service = document.createElement("span");
  service.classList.add("service");
  service.innerText = v.service.free;
  info.appendChild(category);
  info.appendChild(gymName);
  info.appendChild(price);
  info.appendChild(service);

  card.appendChild(info);
  container.appendChild(card);
});
main.appendChild(container);
document.body.appendChild(main);
